theme: jekyll-theme-slate
title: Coral Sun Drifters
collections_dir: collections
collections:
  main:
    output: true
  characters:
    output: true
  npcs:
    output: true
  locations:
    output: true
  sessions:
    output: true
  theories:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
